### 

# Get User via username

GET http://localhost:8080/api/v1/users HTTP/1.1


### 

POST http://localhost:8080/api/v1/users HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "mail",
  "username": "hello"
}


### 

PUT http://localhost:8080/api/v1/user/0 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "mail@hvl.no"
}


### 

DELETE http://localhost:8080/api/v1/user/0 HTTP/1.1


### 

POST http://localhost:8080/api/v1/polls HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "creatorId": 1,
  "question": "Voting via rabbitMQ?",
  "validUntil": "2026-01-01T01:00:00Z",
  "voteOptions": [
    {
      "caption": "Yes",
      "presentationOrder": 0
    },
    {
      "caption": "No",
      "presentationOrder": 1
    }
  ]
}


### 

PUT http://localhost:8080/api/v1/poll/0 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "creatorId": 0,
  "question": "Do you agree?",
  "validUntil": "2026-01-01T01:00:00Z",
  "voteOptions": [
    {
      "caption": "Yes",
      "presentationOrder": 0
    },
    {
      "caption": "No",
      "presentationOrder": 1
    }
  ]
}


### 

GET http://localhost:8080/api/v1/polls HTTP/1.1


### 

DELETE http://localhost:8080/api/v1/poll/10 HTTP/1.1


### 

GET http://localhost:8080/api/v1/votes/10 HTTP/1.1


### 

POST http://localhost:8080/api/v1/votes HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "creatorId": 1,
  "pollId": 10,
  "voteOption": {
    "caption": "Yes",
    "presentationOrder": 0
  }
}
